backend/backend-skincare-2023/Controllers/RoutinesController.cs
using backend_skincare_2023.Models;
using ChatGPT.Net;
using ChatGPT.Net.DTO.ChatGPT;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;



namespace backend_skincare_2023.Controllers
{
    public class RoutinesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<RoutinesController> _logger;
        private readonly string _apiKey;

       
        public RoutinesController(ApplicationDbContext context, ILogger<RoutinesController> logger, IConfiguration configuration)
        {
            _context = context;
            _logger = logger;
            _apiKey = configuration.GetSection("ApiSettings:ApiKey").Value;
        }

       
        [Route("Routines/SkinRoutine")]
        public async Task<IActionResult> SkinRoutine()
        {
            var viewModel = new RoutineText();

            try
            {
               
                var bot = new ChatGpt(_apiKey, new ChatGptOptions
                {
                    Model = "gpt-3.5-turbo",
                    MaxTokens = 1400
                }); ;

                viewModel.Text = await bot.Ask($"Descreva uma rotina de skincare completa com base nessas respostas:");
                
               
                return View(viewModel);
                

            }
            catch (Exception e)
            {
                LogError(e, "Error");
                viewModel.ErrorMessage = "Ocorreu um erro ao obter a rotina. Por favor, tente novamente mais tarde.";
            }

            return View(viewModel);
           

        }



        private void LogError(Exception e, string message)
        {
            
             _logger.LogError(e, message);
        }



        // GET: Routines
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Routines.Include(r => r.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Routines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Routines == null)
            {
                return NotFound();
            }

            var routine = await _context.Routines
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.RoutineId == id);
            if (routine == null)
            {
                return NotFound();
            }

            return View(routine);
        }

        // GET: Routines/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email");
            return View();
        }


        // POST: Routines/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoutineId,RoutineText,CreatedAt,UserId")] Routine routine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(routine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", routine.UserId);
            return View(routine);
        }



        // GET: Routines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Routines == null)
            {
                return NotFound();
            }

            var routine = await _context.Routines.FindAsync(id);
            if (routine == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", routine.UserId);
            return View(routine);
        }


        // POST: Routines/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoutineId,RoutineText,CreatedAt,UserId")] Routine routine)
        {
            if (id != routine.RoutineId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(routine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoutineExists(routine.RoutineId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", routine.UserId);
            return View(routine);
        }


        // GET: Routines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Routines == null)
            {
                return NotFound();
            }

            var routine = await _context.Routines
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.RoutineId == id);
            if (routine == null)
            {
                return NotFound();
            }

            return View(routine);
        }


        // POST: Routines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Routines == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Routines'  is null.");
            }
            var routine = await _context.Routines.FindAsync(id);
            if (routine != null)
            {
                _context.Routines.Remove(routine);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoutineExists(int id)
        {
          return _context.Routines.Any(e => e.RoutineId == id);
        }
    }
}

backend/backend-skincare-2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/images/favicon-32x32.png" type="image/x-icon">
    <link rel="shortcut icon" href="~/images/favicon-32x32.png" type="image/x-icon">
    <title>@ViewData["title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Layout.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.14.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    
</head>

<header class="header">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.png" class="website-logo" width="96" alt="Logo">
            </a>
            <button class="navbar-toggler order-first" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="quemsomos">Quem somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="guiapele">Guia da pele</a>
                    </li>
                </ul>
                <div>
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            var isAdminClaim = User.Claims.FirstOrDefault(c => c.Type == "isAdmin");
                            if (isAdminClaim != null && bool.TryParse(isAdminClaim.Value, out bool isAdmin))
                            {
                                @if (isAdmin)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link active" asp-area="" asp-controller="Users" asp-action="Index">Administrador</a>
                                    </li>
                                    <li class="nav-item ml-auto">
                                        <a class="nav-link text-dark align-right" id="logout" asp-area="" asp-controller="Users" asp-action="Logout">Sair</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item ml-auto">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Routines" asp-action="Index">Minha conta</a>
                                    </li>
                                    <li class="nav-item ml-auto">
                                        <a class="nav-link text-dark align-right" id="logout" asp-area="" asp-controller="Users" asp-action="Logout">Sair</a>
                                    </li>
                                }
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="user-icon align-right" asp-area="" asp-controller="Users" asp-action="Login"><img src="~/images/profile.png" width="18"></a>
                            </li>
                        }
                    </ul>
                </div>



            </div>
        </div>
    </nav>
</header>

<body>


    <div >
        <main role="main">
            @RenderBody()
        </main>
    </div>


    <footer id="footer">
        <div class="container mt-5">
                <div class="row text-center text-xs-center text-sm-center text-md-center">
                    <div class="col-xs-12 col-sm-8" id="footer-text">
                        <p class="copy-right">
                        <a> 2023 SOFT CARE. Todos os direitos reservados.</a>
                        </p>
                        <p class="privacidade"><a asp-area="" asp-controller="Home" asp-action="privacidade">Política de privacidade</a>
                        <p class="terms"><a href="">Termos de uso</a>
                        <p>
                    </div>
                </div>
            <div class="social">
                <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
                <a href="https://es-es.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></i></a>
                <a href="https://twitter.com/?lang=ES" target="_blank"><i class="fab fa-twitter"></i></a>
            </div> 
    </footer>

 

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>